### PR TITLE
fix: update nerdfont symbols

### PR DESCRIPTION
**Pull request by nonetrix**
Successor to https://github.com/catppuccin/rofi/pull/17 fixes all the icons in one PR with https://github.com/loichyan/nerdfix#interactive-patching

### CODE REVIEW

**Comment by nonetrix** [comment]
Can you review this @nekowinston @unseen-ninja @AlphaTechnolog sorry to ping just don't want a repeat of the last where it wasn't noticed really. PR should be no brainer to merge this

**Comment by sgoudham** [comment]
Hey :wave: 

Winston has left the organisation and I don't believe lemon (unseen-ninja) is active at the minute. I'm happy to merge but I feel like we should include somewhere in the README what version of nerdfonts these files are shipping with?

I haven't used nerdfonts in a while since my terminal fallbacks to a symbol font but I believe we can track the versions right?

**Comment by nonetrix** [comment]
Ah sorry my bad, I didn't notice I just looked though few PRs and checked who they where merged by

**Comment by sgoudham** [comment]
No need to apologise! Just letting you know why people might not respond to that ping. I'm unsure if AlphaTechnolog is still active.

**Comment by nonetrix** [comment]
Newest version is `v3.2.1` so I guess just go with that? Maybe something like
# Requirements
- A font patched with at least nerdfonts v3.2.1 or possibly higher
- Rofi

**Comment by nonetrix** [comment]
Another idea is to just setup a Github actions bot to just run nerdfix every so often, of course exclude any files that aren't `.rasi` just incase the weird edge case that somehow a image file for example happens to have bytes that look like nerdfont logo and just say to run newest release. I think that is over engineering though and I haven't played with actions, I doubt there is going to be a major codepoint shift in a while so it would be mostly in vain

**Comment by sgoudham** [comment]
Happy to approve once the README is updated with the requirements as per your testing. 
I think the action is overkill yeah

**Comment by nonetrix** [comment]
Done

**Comment by nonetrix** [comment]
Lemme see if I can somehow combine those commits so it doesn't clutter git log or whatever

**Comment by nonetrix** [comment]
Eh whatever I can't figure it out doesn't matter, I think it might automatically do it anyway when merged? I only have basic idea of how PRs work

**Pull request merged**
