### PR TITLE
fixed nerd-font icons

### PR DESCRIPTION
**Pull request by ronit1996**
Fixed the nerd font icons as the old ones didn't work on the updated nerd fonts, the icons are same just the names got changed in the website.

Ronit Sadhukhan
ronit1996@outlook.com

### CODE REVIEW

**Comment by nonetrix** [comment]
Is this issue present in the [deathemonic](https://github.com/catppuccin/rofi/tree/main/deathemonic) version?

**Comment by nonetrix** [comment]
Also people can check this issue for more information, but TL;DR of it is some of the Unicode codepoints used where not free for use, meaning they where already occupied so some of them where changed around to prevent issues  

https://github.com/ryanoasis/nerd-fonts/issues/1190

**Comment by ronit1996** [comment]
I didn't check the deathmonic version but what I found out is that they had changed the codes for various icons, and hence those codes starting showing different icons.

**Comment by rhiroyuki** [comment]
Running [nerdfix check](https://github.com/loichyan/nerdfix#-usage) it alerted about some obsolete icons.
I had to use [nerdfix fix](https://github.com/loichyan/nerdfix#interactive-patching) to properly display them.

**Comment by nonetrix** [comment]
Is there anything blocking this from being merged?

**Comment by nonetrix** [comment]
> Running [nerdfix check](https://github.com/loichyan/nerdfix#-usage) it alerted about some obsolete icons (for basic and the deathmonic versions). I had to use [nerdfix fix](https://github.com/loichyan/nerdfix#interactive-patching) to properly display them.

I will submit another PR with everything fixed as OP doesn't seem active

**Comment by sgoudham** [comment]
Closing as #22 supersedes this

**Pull request closed without merging**
